### ISSUE TITLE
Has the anisotropic property been lost?

### ISSUE THREAD

**Issue by CanCanZeng** [ZhentaoHuang/Textured-GS#1]
Hello, I have read your paper and think this idea is very creative. This idea has the potential to combine 3DGS with traditional textured mesh, not only improving 3DGS's ability to fit high-frequency textures, but also accelerating rendering by reducing the number of Gaussian primitives.
I have a question: According to Figure 2 in your paper, the calculation of color is based on the intersection point between the light ray and the ellipsoid. If this is the case, it is equivalent to different directions of light rays. As long as its intersection point with the ellipsoid is the same, the color will also be the same. Does this means we losing the color anisotropy of 3DGS?

**Comment by ZhentaoHuang** [comment]
Hi, thanks for your interests on our work! And yes, Textured-GS will output same color only if the intersection point is the same. In the future work, we are considering combining view-dependent GS with Textured-GS to cover this issue.

**Comment by CanCanZeng** [comment]
Thank you for your reply, it answered my question.
